// packages/devpage-framework/src/angular/components/navigation.component.ts
import { ChangeDetectionStrategy, Component } from "@angular/core"
import { RouterLink, RouterLinkActive } from "@angular/router"
import { ForesightDirective } from "@foresightjs/angular"
import { routeImports } from "../routes"

/**
 * Sticky top nav. Each link carries `[fsForesight]` so predicting it warms the
 * target route's lazy chunk before the click — the directive's headline use case.
 */
@Component({
  selector: "app-navigation",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [RouterLink, RouterLinkActive, ForesightDirective],
  template: `
    <header class="bg-white border-b border-gray-300 sticky top-0 z-10">
      <div class="max-w-6xl mx-auto px-6 py-3 flex items-center justify-between">
        <a
          routerLink="/"
          [fsForesight]="prefetch['/']"
          fsForesightName="nav-logo"
          class="text-base font-semibold text-gray-900"
        >
          ForesightJS Angular
        </a>
        <nav class="flex items-center gap-4 text-sm">
          <a
            routerLink="/"
            routerLinkActive="text-gray-900 font-medium"
            [routerLinkActiveOptions]="{ exact: true }"
            [fsForesight]="prefetch['/']"
            fsForesightName="nav-home"
            class="text-gray-700 hover:text-gray-900"
          >
            Home
          </a>
          <a
            routerLink="/elements"
            routerLinkActive="text-gray-900 font-medium"
            [fsForesight]="prefetch['/elements']"
            fsForesightName="nav-elements"
            class="text-gray-700 hover:text-gray-900"
          >
            Elements
          </a>
          <a
            routerLink="/mass"
            routerLinkActive="text-gray-900 font-medium"
            [fsForesight]="prefetch['/mass']"
            fsForesightName="nav-mass"
            class="text-gray-700 hover:text-gray-900"
          >
            Mass test
          </a>
          <a
            routerLink="/events"
            routerLinkActive="text-gray-900 font-medium"
            [fsForesight]="prefetch['/events']"
            fsForesightName="nav-events"
            class="text-gray-700 hover:text-gray-900"
          >
            Events
          </a>
        </nav>
      </div>
    </header>
  `,
})
export class NavigationComponent {
  // The directive accepts a bare callback; predicting the link fires the matching
  // route import so its chunk is cached by the time the user clicks.
  protected readonly prefetch = routeImports
}

// packages/devpage-react/src/components/Navigation.tsx
import { useButtonActions, useReactivateAfter } from "../stores/ButtonStateStore"
import { useDebug } from "../contexts/DebugContext"
import { ForesightLink } from "./ForesightLink"
import { routeImports } from "../routes"

export const Navigation = () => {
  const actions = useButtonActions()
  const reactivateAfter = useReactivateAfter()
  const { isDebugActive, toggleDebug } = useDebug()

  return (
    <header className="bg-white border-b border-gray-300 sticky top-0 z-10">
      <div className="max-w-6xl mx-auto px-6 py-3 flex items-center justify-between">
        <ForesightLink
          to="/"
          name="nav-logo"
          className="text-base font-semibold text-gray-900"
          onPrefetch={() => routeImports["/"]()}
        >
          ForesightJS Dev
        </ForesightLink>
        <nav className="flex items-center gap-4 text-sm">
          <ForesightLink
            to="/"
            name="nav-home"
            className="text-gray-700 hover:text-gray-900"
            onPrefetch={() => routeImports["/"]()}
          >
            Home
          </ForesightLink>
          <ForesightLink
            to="/elements"
            name="nav-elements"
            className="text-gray-700 hover:text-gray-900"
            onPrefetch={() => routeImports["/elements"]()}
          >
            Elements
          </ForesightLink>
          <ForesightLink
            to="/mass"
            name="nav-mass"
            className="text-gray-700 hover:text-gray-900"
            onPrefetch={() => routeImports["/mass"]()}
          >
            Mass test
          </ForesightLink>
          <span className="w-px h-5 bg-gray-300" />
          <label className="flex items-center gap-1 text-xs text-gray-700">
            Reactivate
            <input
              type="number"
              min={0}
              step={500}
              value={reactivateAfter}
              onChange={e => actions.setReactivateAfter(Number(e.target.value))}
              className="w-20 px-1 py-0.5 text-xs border border-gray-400"
            />
            ms
          </label>
          <button
            onClick={toggleDebug}
            className="px-2 py-1 text-xs border border-gray-400 text-gray-800 hover:bg-gray-100"
            title="Toggle ForesightDevtools control panel"
          >
            Debug: {isDebugActive ? "on" : "off"}
          </button>
          <button
            onClick={actions.resetAll}
            className="px-2 py-1 text-xs border border-gray-400 text-gray-800 hover:bg-gray-100"
          >
            Reset
          </button>
        </nav>
      </div>
    </header>
  )
}
