// packages/devpage-react/src/App.tsx
import { lazy, Suspense } from "react"
import { BrowserRouter as Router, Routes, Route, Outlet } from "react-router-dom"
import { Navigation } from "./components/Navigation"
import { DebugProvider } from "./contexts/DebugContext"

const Home = lazy(() => import("./pages/home"))
const Elements = lazy(() => import("./pages/elements"))
const Mass = lazy(() => import("./pages/mass"))

const Layout = () => (
  <div className="min-h-screen bg-stone-50 text-gray-900">
    <Navigation />
    <Suspense>
      <Outlet />
    </Suspense>
  </div>
)

const App = () => {
  return (
    <DebugProvider>
      <Router>
        <Routes>
          <Route element={<Layout />}>
            <Route path="/" element={<Home />} />
            <Route path="/elements" element={<Elements />} />
            <Route path="/mass" element={<Mass />} />
          </Route>
        </Routes>
      </Router>
    </DebugProvider>
  )
}

export default App

// packages/devpage-framework/src/angular/app.component.ts
import { ChangeDetectionStrategy, Component } from "@angular/core"
import { RouterOutlet } from "@angular/router"
import { NavigationComponent } from "./components/navigation.component"

@Component({
  selector: "app-root",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [RouterOutlet, NavigationComponent],
  template: `
    <div class="min-h-screen bg-stone-50 text-gray-900">
      <app-navigation />
      <router-outlet />
    </div>
  `,
})
export class AppComponent {}
