// packages/foresightjs-react/src/components/Foresight.tsx
import type { ComponentPropsWithoutRef, CSSProperties, ElementType, ReactNode } from "react"
import type { ForesightElementState } from "js.foresight"
import { useForesightRegistration } from "../hooks/useForesightRegistration"
import { useForesightState } from "../hooks/useForesightState"
import { useForesightDataAttributes } from "../hooks/useForesightDataAttributes"
import type { ForesightOptions, ForesightResult } from "../types"

/**
 * Component form of the registration options. The foresight `name` option is
 * exposed as `foresightName` so the HTML `name` attribute (on `input`,
 * `button`, `select`, ...) can be forwarded to the element in the `as` form.
 */
export type ForesightComponentOptions = Omit<ForesightOptions, "name"> & {
  foresightName?: string
}

export type ForesightProps<T extends HTMLElement = HTMLElement> = ForesightComponentOptions & {
  as?: never
  className?: never
  style?: never
  children: (result: ForesightResult<T>) => ReactNode
}

export type ForesightAsProps<E extends ElementType> = ForesightComponentOptions & {
  as: E
  children?: ReactNode | ((state: ForesightElementState) => ReactNode)
  className?: string | ((state: ForesightElementState) => string)
  style?: CSSProperties | ((state: ForesightElementState) => CSSProperties | undefined)
} & Omit<
    ComponentPropsWithoutRef<E>,
    keyof ForesightComponentOptions | "as" | "children" | "className" | "style"
  >

/**
 * Component form of useForesight: one instance, one registration.
 *
 * With `as`, it renders that element itself and forwards the remaining props
 * to it, including the HTML `name` attribute (the foresight name is
 * `foresightName`). It mirrors the element state onto `data-predicted`,
 * `data-callback-running` and `data-status` attributes via direct DOM
 * mutation, so plain CSS can style predictions. `children`,
 * `className` and `style` may also be functions of the reactive state:
 *
 * ```tsx
 * <Foresight
 *   as="button"
 *   callback={() => prefetch("/checkout")}
 *   onClick={checkout}
 *   className="checkout data-predicted:outline-amber-500"
 * >
 *   Checkout
 * </Foresight>
 * ```
 *
 * With a function as children and no `as`, it renders nothing itself and
 * passes the reactive state plus the elementRef to attach, giving full
 * control over the markup:
 *
 * ```tsx
 * <Foresight callback={() => prefetch(item.url)}>
 *   {({ elementRef, isPredicted }) => (
 *     <a ref={elementRef} href={item.url} className={isPredicted ? "predicted" : ""}>
 *       {item.name}
 *     </a>
 *   )}
 * </Foresight>
 * ```
 */
export function Foresight<T extends HTMLElement = HTMLElement>(props: ForesightProps<T>): ReactNode
export function Foresight<E extends ElementType>(props: ForesightAsProps<E>): ReactNode
export function Foresight(props: ForesightProps | ForesightAsProps<ElementType>): ReactNode {
  return props.as ? <ForesightElement {...props} /> : <ForesightRenderProp {...props} />
}

/**
 * Runtime list of every foresight option prop, used to split options from DOM
 * props. The `satisfies` clause keeps it exhaustive: when the core options
 * type gains a key this stops compiling until the key is added here, so a new
 * option can never silently fall through to the DOM element.
 */
const FORESIGHT_OPTION_KEYS = {
  callback: true,
  hitSlop: true,
  foresightName: true,
  meta: true,
  reactivateAfter: true,
  enabled: true,
} as const satisfies Record<keyof ForesightComponentOptions, true>

// Change name to foresightName for the component form, so the HTML name attribute can be forwarded to the element in the `as` form.
const toRegistrationOptions = ({
  foresightName,
  ...options
}: ForesightComponentOptions): ForesightOptions => ({
  ...options,
  name: foresightName,
})

/** Splits the flat props of the `as` form into options and DOM props. */
const splitForesightProps = <P extends object>(props: P) => {
  const optionProps: Record<string, unknown> = {}
  const domProps: Record<string, unknown> = {}
  for (const [key, value] of Object.entries(props)) {
    if (key in FORESIGHT_OPTION_KEYS) {
      optionProps[key] = value
    } else {
      domProps[key] = value
    }
  }

  return {
    options: toRegistrationOptions(optionProps as ForesightComponentOptions),
    domProps,
  }
}

const ForesightRenderProp = <T extends HTMLElement>({
  children,
  ...options
}: ForesightProps<T>): ReactNode => {
  const { elementRef, registerResults } = useForesightRegistration<T>(
    toRegistrationOptions(options)
  )
  const state = useForesightState(registerResults, true)

  return children({ elementRef, ...state })
}

const ForesightElement = (props: ForesightAsProps<ElementType>): ReactNode => {
  const { as: Tag, children, className, style, ...flatProps } = props
  const { options, domProps } = splitForesightProps(flatProps)

  const { element, elementRef, registerResults } = useForesightRegistration(options)

  // Subscribe only when something actually reads the state, so a fully static
  // element does not re-render on state changes (the data attributes are
  // mirrored onto the DOM directly by useForesightDataAttributes).
  const readsState =
    typeof children === "function" || typeof className === "function" || typeof style === "function"

  const state = useForesightState(registerResults, readsState)
  useForesightDataAttributes(element, registerResults)

  return (
    <Tag
      {...domProps}
      className={typeof className === "function" ? className(state) : className}
      style={typeof style === "function" ? style(state) : style}
      ref={elementRef}
    >
      {typeof children === "function" ? children(state) : children}
    </Tag>
  )
}

// packages/foresightjs-vue/src/components/Foresight.vue
<script setup lang="ts">
import { computed, reactive, shallowRef, watchEffect } from "vue"
import { useForesight } from "../composables/useForesight"
import { resolveElement } from "../utils/resolveElement"
import { applyDataAttributes, removeDataAttributes } from "../utils/dataAttributes"
import type { ForesightOptions, ForesightProps, ForesightSlotProps, MaybeElement } from "../types"

defineSlots<{
  default?: (props: ForesightSlotProps) => unknown
}>()

defineOptions({ name: "Foresight" })

const {
  as,
  callback,
  foresightName,
  hitSlop,
  meta,
  reactivateAfter,
  enabled = undefined,
} = defineProps<ForesightProps>()

// The `satisfies` clause keeps this mapping exhaustive: when the core options
// type gains a key this stops compiling until the key is added here (and as a
// prop), so a new option can never silently fall through to the DOM element.
const options = computed(
  () =>
    ({
      callback,
      hitSlop,
      name: foresightName,
      meta,
      reactivateAfter,
      enabled,
    }) satisfies Record<keyof ForesightOptions, unknown> as ForesightOptions
)

const { elementRef, ...stateRefs } = useForesight(options)

// Track the resolved element for the data-attribute mirror.
const element = shallowRef<Element | null>(null)
const setRef = (el: MaybeElement) => {
  const resolved = resolveElement(el) ?? null
  if (resolved === element.value) {
    return
  }

  if (element.value) {
    removeDataAttributes(element.value)
  }

  element.value = resolved
  elementRef(el)
}

// reactive() unwraps the state refs; reads inside the slot body or the
// watchEffect are tracked fine-grained, so a slot that never reads state never
// re-renders on state changes.
const slotProps: ForesightSlotProps = reactive({ ...stateRefs, elementRef: setRef })

// `as` form only: mirror state onto data-* attributes via direct DOM mutation,
// so [data-predicted] CSS works without any re-render.
watchEffect(() => {
  if (!as || !element.value) {
    return
  }

  applyDataAttributes(element.value, slotProps)
})
</script>

<template>
  <component :is="as" v-if="as" :ref="setRef">
    <slot v-bind="slotProps" />
  </component>
  <slot v-else v-bind="slotProps" />
</template>
