// packages/devpage-framework/src/react/components/ui/ForesightStats.tsx
type ForesightStatsProps = {
  isPredicted: boolean
  hitCount: number
  isCallbackRunning: boolean
  status: string | undefined
}

const row = (label: string, value: React.ReactNode) => {
  return (
    <div className="flex justify-between px-2 py-1">
      <span className="text-gray-500">{label}</span>
      <span className="text-gray-900">{value}</span>
    </div>
  )
}

const ForesightStats = ({
  isPredicted,
  hitCount,
  isCallbackRunning,
  status,
}: ForesightStatsProps) => {
  return (
    <div className="w-56 font-mono text-[11px] border border-gray-300 divide-y divide-gray-200 bg-white">
      {row("predicted", isPredicted ? "yes" : "no")}
      {row("hits", hitCount)}
      {row("cb running", isCallbackRunning ? "yes" : "no")}
      {row("status", status ?? "-")}
    </div>
  )
}

export default ForesightStats

// packages/devpage-vue/src/components/ForesightStats.vue
<script setup lang="ts">
defineProps<{
  isPredicted: boolean
  hitCount: number
  isCallbackRunning: boolean
  status: string | undefined
}>()
</script>

<template>
  <div class="w-56 font-mono text-[11px] border border-gray-300 divide-y divide-gray-200 bg-white">
    <div class="flex justify-between px-2 py-1">
      <span class="text-gray-500">predicted</span>
      <span class="text-gray-900">{{ isPredicted ? "yes" : "no" }}</span>
    </div>
    <div class="flex justify-between px-2 py-1">
      <span class="text-gray-500">hits</span>
      <span class="text-gray-900">{{ hitCount }}</span>
    </div>
    <div class="flex justify-between px-2 py-1">
      <span class="text-gray-500">cb running</span>
      <span class="text-gray-900">{{ isCallbackRunning ? "yes" : "no" }}</span>
    </div>
    <div class="flex justify-between px-2 py-1">
      <span class="text-gray-500">status</span>
      <span class="text-gray-900">{{ status ?? "—" }}</span>
    </div>
  </div>
</template>
